---
resources:
  - name: demo-repo
    type: git
    source:
      uri: https://github.com/michaellihs/concourse-demo.git
      branch: master
  - name: busy-box
    type: docker-image
    source: {repository: busybox}


jobs:
  - name: hello-world
    plan:
      - get: busy-box
      - get: demo-repo
      - task: hello-world
        image: busy-box
        config:
          platform: linux
          file: demo-repo/tutorial-3/hello-world.yml
